name: Build and Deploy Web

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Install dependencies
      run: pnpm install
      working-directory: web

    - name: Build
      run: pnpm run build
      working-directory: web
      
    - name: Deploy to Aliyun
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.ALIYUN_HOST }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        password: ${{ secrets.ALIYUN_PASSWORD }}
        port: 22
        source: "web/build/*"
        target: "/root/JARVIS/web"
        strip_components: 2
      

