name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # web
      - name: web - copy to aliyun
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          port: 22
          source: "web/*"
          target: "/opt/JARVIS/web"
          strip_components: 1

      - name: web - build and restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          port: 22
          script: |
            cd /opt/JARVIS/web
            pnpm install
            pnpm run build
            pm2 restart web || pm2 start npm --name "web" -- start