name: Build and Deploy Web

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Copy to Aliyun
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.ALIYUN_HOST }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        password: ${{ secrets.ALIYUN_PASSWORD }}
        port: 22
        source: "web/*"
        target: "/root/JARVIS/web"
        strip_components: 2
