name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # web
      - name: web - copy to aliyun
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          port: 22
          source: "web/*"
          target: "/opt/JARVIS/web"
          strip_components: 1

      - name: web - build and restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          port: 22
          script: |
            cd /opt/JARVIS/web
            pnpm install
            pnpm run build
            pm2 restart web || pm2 start npm --name "web" -- start

      # ai
      - name: ai - set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.2"

      - name: ai - install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
        working-directory: ai

      - name: ai - build executable with PyInstaller
        run: |
          pyinstaller -F ./main.py --add-binary "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/py_mini_racer:." --add-binary "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/akshare:./akshare"
        working-directory: ai

      - name: ai - kill old process
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }} 
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}  
          port: 22
          script: |
            if pgrep -f "/opt/JARVIS/ai/dist/main" > /dev/null; then
              echo "killing old process..."
              killall "/opt/JARVIS/ai/dist/main"
              sleep 2
            fi

      - name: ai - prepare target directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          port: 22
          script: |
            rm -rf /opt/JARVIS/ai/dist
            mkdir -p /opt/JARVIS/ai

      - name: ai - copy to aliyun
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          port: 22
          source: "ai/*"
          target: "/opt/JARVIS/ai"
          strip_components: 1

      - name: ai - restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }} 
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}  
          port: 22
          script: |
            nohup /opt/JARVIS/ai/dist/main > /dev/null 2>&1 &