name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
        working-directory: ai

      - name: Build executable with PyInstaller
        run: |
          pyinstaller -D ./main.py --add-binary "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\py_mini_racer;." --add-binary "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\akshare;.\akshare"
        working-directory: ai

      - name: Copy executable to Aliyun
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          port: 22
          source: "ai/dist/main"
          target: "/opt/JARVIS/ai"
          strip_components: 1
