name: Deploy Web

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Aliyun
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          port: 22
          source: "web/*"
          target: "/opt/JARVIS/web"
          strip_components: 2
          script: |
            cd /opt/JARVIS/web
            pnpm install
            pnpm run build
            pnpm start
